installCRDs: true

nodeSelector:
  workload: system

webhook:
  nodeSelector:
    workload: system

cainjector:
  nodeSelector:
    workload: system

startupapicheck:
  enabled: false

prometheus:
  enabled: true