prometheusOperator:
  nodeSelector:
    workload: system

  admissionWebhooks:
    patch:
      nodeSelector:
        workload: system

grafana:
  nodeSelector:
    workload: system

prometheus:
  prometheusSpec:
    nodeSelector:
      workload: system

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      workload: system

kube-state-metrics:
  nodeSelector:
    workload: system

prometheus-node-exporter:
  nodeSelector:
    workload: system

installCRDs: true