driver:
  kind: modern_ebpf

falcoctl:
  artifact:
    install:
      enabled: true
    follow:
      enabled: true

falcosidekick:
  enabled: true

serviceMonitor:
  create: true

collectors:
  enabled: true

tolerations:
  - operator: Exists